config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"
  get 'home/about' => 'homes#about'
  get 'home/rank' => 'homes#rank'

  resources :tweets do
   resource :favorites, only: [:create, :destroy]
   resources :tweet_comments, only: [:create, :destroy]
 end

  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
 end

  get 'movies/search'
  get 'movies/show'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :tweet

end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
 #フォロー機能のための記載
 #class_name: "User"を定義することでUserテーブルのレコードを参照する
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/tweet.rb
class Tweet < ApplicationRecord

  validates :title, presence: true
  validates :description, presence: true

  acts_as_taggable

  belongs_to :user
  attachment :image

  has_many :tweet_comments, dependent: :destroy

  has_many :favorites, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end


end

app/models/tweet_comment.rb
class TweetComment < ApplicationRecord
  # 指定したカラムに何も値が入っていなかったときには保存されない
  validates :rate, presence: true

  belongs_to :user
  belongs_to :tweet

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  validates :last_name, presence: true
  validates :first_name, presence: true

  has_many :tweet_comments, dependent: :destroy

  has_many :tweets, dependent: :destroy
  attachment :profile_image

  has_many :favorites, dependent: :destroy
  has_many :favorite_tweets, through: :favorites, source: :tweet

  has_many :reverth_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverth_of_relationships, source: :follower
  #フォローされた時の関係を通じて参照→followed_idをフォローしている人

  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  #フォローした際の関係を通じて参照→follower_idをフォローしている人

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end

  def rank
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
 #TMDBを使用するために下記を記載
 #rails cを使用しコンソール上でTmdb::Api.key("6202f5cb38f1e6aafa8bd900346a9106")
 # Tmdb::Api.language("ja")を打ち込んで一度読み込ませる必要がある
  require 'themoviedb-api'

  Tmdb::Api.key(ENV["TMDB_API_KEY"])
  Tmdb::Api.language("ja")

  def search
  end

  def show
  end
end

app/controllers/rater_controller.rb
class RaterController < ApplicationController

  def create
    if user_signed_in?
      obj = params[:klass].classify.constantize.find(params[:id])
      obj.rate params[:score].to_f, current_user, params[:dimension]

      render :json => true
    else
      render :json => false
    end
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    @tweets = Tweet.all.page(params[:page]).reverse_order
    if params[:tag_name]
     @tweets = Tweet.tagged_with("#{params[:tag_name]}").page(params[:page]).reverse_order
    end
  end

  def show
    @tweet = Tweet.find(params[:id])
    @tweet_comment = TweetComment.new
  end

  def new
    @tweet = Tweet.new
  end

  def edit
    @tweet = Tweet.find(params[:id])
    if @tweet.user == current_user
      render :edit
    else
      redirect_to user_path(current_user)
    end
  end

  def create
    @tweet = Tweet.new(tweets_params)
    @tweet.score = Language.get_data(tweets_params[:description])  #この行を追加
    @tweet.user_id = current_user.id
    if @tweet.save
      redirect_to tweets_path, notice: "投稿完了！"
    else
      @tweets = Tweet.all
      render :new
    end
  end

  def update
    @tweet = Tweet.find(params[:id])
    if @tweet.update(tweets_params)
      redirect_to user_path(current_user), notice: "You have update tweet succssfully"
    else
      render :edit
    end
  end

  def destroy
    @tweet = Tweet.find(params[:id])
    @tweet.destroy
    redirect_to user_path(current_user)
  end

  private
  def tweets_params
   params.require(:tweet).permit(:title, :description, :image, :tag_list)
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new

  end

  def index
  end

  def show
    @user = User.find(params[:id])
    @tweet = @user.tweets
    @favorite_tweets = @user.favorite_tweets
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render :edit
    else
      redirect_to user_path(current_user)
    end
  end

  def create
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(current_user), notice: "You have update user succssfully."
    else
      render :edit
    end
  end

  def destroy
  end


  private
  def user_params
    params.require(:user).permit(:last_name, :first_name, :profile_image, :introduction)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/tweet_comments_helper.rb
module TweetCommentsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/tweets/_index.html.erb
<!--eachはdivに入れずに記載する-->
<% tweet.each do |tweet| %>
  <div class="row d-flex justify-content-between no-gutters border border-dark bg-light bg-gradient mt-4">
    <div class="col-lg-6 col-sm-6 col-md-6 col-sm-6">
      <%= attachment_image_tag tweet, :image, fallback: "no_image_icon.jpg", size:"auto", class:"tweet-image" %>
    </div>
    <div class="col-md-5 col-sm-5 card-body position-relative">
      <% if tweet.user.id == current_user.id %>
        <h4 class="card-title text-center"><%= link_to tweet.title, tweet_path(tweet), class:'hoge',data: {"turbolinks"=>false} %></h4>
      <% else %>
        <h4 class="card-title text-center"><%=tweet.title %></h4>
      <% end %>
      <div class="card-text text-center mb-5"><%= tweet.description %></div>
       <% if 0 > tweet.score %>
        <p>
          <span class="sentiment-score text-info">悲しかったね<%= tweet.score %></span>
        </p>
        <% else %>
        <p>
          <span class="sentiment-score text-success">良かったね<%= tweet.score %></span>
        </p>
        <% end %>
      <% if tweet.user.id == current_user.id %>
        <%= link_to "編集", edit_tweet_path(tweet), class: "btn btn-primary" %>
        <%= link_to "削除", tweet_path(tweet), class:"btn btn-danger" ,method: :delete, data: {confirm: "削除しますか？"} %>
      <% end %>
    </div>
  </div>
<%end%>

app/views/tweets/_tag_list.html.erb
<% tag_list.each do |tag| %>
<span class="badge badge-primary mr-1 p-2">tag</span>
<% end %>

app/views/tweets/edit.html.erb
<div class="container jumbotron position-relative">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 pt-10">
      <h2>投稿編集</h2>
      <%= form_with model:@tweet, local:true do |f| %>
      <div class="field">
        <label class="image">投稿画像</label>
        <%= f.attachment_field :image, class:"form-control-file" %>
      </div>
      <div class="field">
        <%= f.label "タイトル" %><br />
        <%= f.text_field :title, autofocus: true, autocomplete: "title", placeholder: "タイトル" %>
      </div>

      <div class="form-group">
       <%= f.label :tag_list, "タグ" %><br>※カンマで区切ると複数のタグを登録できます
       <%= f.text_field :tag_list, value: @tweet.tag_list.join(','), class: "form_control" %>
      </div>

      <div class="field">
        <%= f.label "紹介文" %><br />
        <%= f.text_area :description, autofocus: true, autocomplete: "description", size: "100x5", placeholder: "紹介文" %>
      </div>
      <div class="pt-2">
        <%= f.submit class: "btn btn-success" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/tweets/index.html.erb
<div class="container mt-4 position-relative">
<% @tweets.each do |tweet| %>
  <div class="row no-gutters border border-dark bg-light bg-gradient mt-4">
    <div class="col-md-6 col-lg-6 col-sm-6">
      <%= attachment_image_tag tweet, :image, fallback: "no_image_icon.jpg", class:"tweet-image" %>
    </div>
      <div class="col-md-6 pr-3 mt-3 position-relative">
        <% if user_signed_in? %>
        <!--link_toの中に遷移先の画面のturbolinkを切る記述を追加することでjavascriptをちゃんと動作するようにした-->
          <h3 class="card-title text-center"><%= link_to tweet.title, tweet_path(tweet.id), data: {"turbolinks"=>false} %></h3>
        <% else %>
         <h3 class="text-center"><%= tweet.title %></h3>
        <% end %>
        <div class="pb-5">
          <h4 class="text-start text-break"><%= tweet.description %></h4>
        </div>
        <div class="row d-flex flex-column">
          <p>
            タグ:
            <% tweet.tag_list.each do |tweet_tag| %>
             <%= link_to tweet_tag, tweets_path(tag_name: tweet_tag) %>
            <% end %>
          </p>
          <% if 0 < tweet.score %>
           <p>
             <span class="sentiment-score text-success">良かったね<%= tweet.score %></span>
            </p>
          <% else %>
            <p>
             <span class="sentiment-score text-info">悲しかったね<%= tweet.score %></span>
            </p>
          <% end %>
            <%= attachment_image_tag tweet.user, :profile_image, size:"60x60", fallback: "no_image_icon.jpg", class:"rounded-circle" %>
          <!--last_nameとfirst_nameを足して表示することでフルネームとして表示-->
          <% if user_signed_in? %>
          <p>
            <%= link_to tweet.user.last_name + tweet.user.first_name, user_path(tweet.user.id) %>
          </p>
          <% else %>
            <%= tweet.user.last_name + tweet.user.first_name %>
          <% end %>
          <div id="favorite-btn-<%= tweet.id %>">
            <%= render "favorites/favorite", tweet: tweet %>
          </div>
        </div>
      </div>
  </div>
<%end%>
  <div class="mt-3 d-flex justify-content-center">
    <%= paginate @tweets %>
  </div>

app/views/tweets/new.html.erb
<div class="container jumbotron mt-3 position-relative">
   <h1>新規投稿</h1>
<%= form_with model:@tweet, local:true do |f| %>
<%= render 'layouts/error_messages', model: f.object %>
　<div class="form-group">
    <%= f.label :image, "画像" %>
    <%= f.attachment_field :image, class:"form-control-file" %>
  </div>
 <div class="form-group">
    <%= f.label :title, "タイトル" %><br>
    <%= f.text_field :title %>
 </div>
 <div class="form-group">
    <%= f.label :description, "おすすめポイント・見どころ" %><br>
    <%= f.text_area :description, size: "100x5" %>
 </div>
 <div class="form-group">
    <%= f.label :tag_list, "タグ" %> ※カンマで区切ると複数のタグを登録できます<br>
    <%= f.text_field :tag_list, value: @tweet.tag_list.join(','), class: "form_control" %>
 </div>
  <%= f.submit '投稿' %>
<% end %>

</div>

app/views/tweets/show.html.erb
<div class="container mt-2 jumbotron position-relative">
  <div class="row">
    <div class="col-md-1 col-lg-1 col-sm-1 mt-1">
      <%= attachment_image_tag @tweet.user, :profile_image, size:"60x60", fallback: "no_image_icon.jpg", class:"rounded-circle" %>
    </div>
    <div class="col-md-11 col-lg-11 col-sm-11 mt-3 ">
      <%= link_to @tweet.user.last_name + @tweet.user.first_name, user_path(@tweet.user.id) %>
      <div class="d-flex justify-content-between">
        <div>
          <% if current_user != @tweet.user %>
            <% if current_user.following?(@tweet.user) %>
             <%= link_to "フォロー外す", user_relationships_path(@tweet.user.id), method: :delete, class: "btn btn-primary" %>
            <% else %>
             <%= link_to "フォローする", user_relationships_path(@tweet.user.id), method: :post, class: "btn btn-success" %>
            <% end %>
          <% end %>
        </div>
        <div id="favorite-btn-<%= @tweet.id %>">
          <%= render "favorites/favorite", tweet: @tweet %>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <%= attachment_image_tag @tweet, :image, fallback: "no_image_icon.jpg", class:"card-img-top" %>
    </div>
    <div class="col">
      <div>
        <h6>タイトル</h6>
      </div>
      <div>
        <h4><%= @tweet.title %></h4>
      </div>
      <div>
        <h6>見どころ・ポイント</h6>
      </div>
      <h4><%= @tweet.description %></h4><br>
        <% if 0 > @tweet.score %>
        <p>
          <span class="sentiment-score text-info">悲しかったね<%= @tweet.score %></span>
        </p>
        <% else %>
        <p>
          <span class="sentiment-score text-success">良かったね<%= @tweet.score %></span>
        </p>
        <% end %>
      <!-- モーダルエリアここから -->
      <div class="col">
        <button id="openModal">コメント</button>
      </div>
      <section id="modalArea" class="modalArea">
         <div id="modalBg" class="modalBg"></div>
          <div class="modalWrapper">
            <div class="col">
              <%= form_with(model:[@tweet, @tweet_comment], local: true) do |f| %>
                <div id="stars">
                 <label>評価</label>
                </div>
               <%= f.text_area :comment, rows:'5',placeholder: "コメントをここに" %>
               <%= f.submit "コメントする" %>
              <% end %>
              <!--raty(評価機能)のjsはここに記載する-->
              <script>
                $('#stars').raty({
                 starOn: "<%= asset_path('star-on.png') %>",
                 starOff: "<%= asset_path('star-off.png') %>",
                 starHalf: "<%= asset_path('star-half.png') %>",
                 scoreName: 'tweet_comment[rate]' //登録するモデル名とカラム名を記述
                });
              </script>
            </div>
            <div id="closeModal" class="closeModal">
             ×
            </div>
          </div>
        </section>
      <!-- モーダルエリアここまで -->
      <div id="comment-<%= @tweet.id %>" class="mt-2">
        コメント件数：<%= @tweet.tweet_comments.count %>
      </div>
    </div>
  </div>
  <div class="row">
    <div id="tweet-comment-<%= @tweet.id %>"  class="col">
      <%= render "tweet_comments/index", tweet_comments: @tweet.tweet_comments %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class='container jumbotron position-relative'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 pt-10">
      <h2>会員情報編集</h2>
      <%= form_with model:@user, local:true do |f| %>
        <%= render 'layouts/error_messages', model: f.object %>
        <div class="field">
          <label class="user_image">プロフィール画像</label>
          <%= f.attachment_field :profile_image, class:"form-control-file" %>
        </div>
        <div class="field">
         <%= f.label "名前" %><br />
         <%= f.text_field :last_name, autofocus: true, autocomplete: "last_name", placeholder: "(姓)" %>
         <%= f.text_field :first_name, autofocus: true, autocomplete: "first_name", placeholder: "(名)" %>
        </div>
        <div class="field">
         <%= f.label "生年月日" %><br />
         <%= f.date_select :birth_date, use_month_numbers: true, start_year: 1930, end_year: (Time.now.year - 10), default: Date.new(1989,1,1) %>
        </div>
        <div class="field">
          <%= f.label :introduction %><br />
          <%= f.text_area :introduction, autofocus: true, autocomplete: "introduction", size: "100x5" , placeholder: "自己紹介" %>
        </div>
        <div class="pt-2">
          <%= f.submit class: 'btn btn-success' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-lg-3 col-md-3 col-sm-3 mt-3 h-25 d-inline-block jumbotron'>
      <table class='table'>
        <tr><%= attachment_image_tag @user, :profile_image, size: "100x100", fallback: "no_image_icon.jpg" %></tr>
        <tr>
          <th><%= @user.last_name %> <%= @user.first_name %></th>
        </tr>
        <tr>
          <th><%= @user.introduction %></th>
        </tr>
      </table>
       <%= link_to '',edit_user_path(@user),class: "btn btn-outline-secondary btn-block fas fa-user-cog bg-light" %>
       <% if current_user != @user %>
          <% if current_user.following?(@user) %>
           <div>
             <%= link_to "フォロー外す", user_relationships_path(@user.id), method: :delete, class: "btn btn-primary mt-3" %>
           </div>
          <% else %>
          <div>
            <%= link_to "フォローする", user_relationships_path(@user.id), method: :post, class: "btn btn-success mt-3" %>
          </div>
          <% end %>
          <%= link_to "フォロワー一覧", user_followers_path(@user), class: "btn btn-success mt-3" %>
        <% else %>
         <%= link_to "フォロワー一覧",  user_followings_path(@user), class: "btn btn-success mt-3"%>
        <% end %>
    </div>
    <div class="col-md-9">
    　<%= render 'tweets/index', tweet: @tweet %>
  　</div>
  　<div class="container-fluid jumbotron position-relative pt-0">
  　  <h3>お気に入り投稿一覧</h3>
  　  <table class="table">
        <thead class="thead-dark">
          <tr>
           <th>タイトル</th>
           <th>投稿者</th>
           <th>投稿日</th>
          </tr>
        </thead>
        <tbody class="border border-dark">
          <% @favorite_tweets.each do |tweet|%>
          <tr>
            <td class="border border-dark border-right-0"> <%= link_to tweet.title, tweet_path(tweet.id), data: {"turbolinks"=>false} %></td>
            <td class="movie-rate border border-dark border-left-0 border-right-0"><%= tweet.user.last_name + tweet.user.first_name %></td>
            <td class="border border-dark border-right-0 border-dark border-left-0"><%= tweet.created_at %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
  　</div>
  </div>
</div>