config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"
  get 'home/about' => 'homes#about'
  get 'home/rank' => 'homes#rank'

  resources :tweets do
   resource :favorites, only: [:create, :destroy]
   resources :tweet_comments, only: [:create, :destroy]
 end

  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
 end

  get 'movies/search'
  get 'movies/show'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :tweet

end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
 #フォロー機能のための記載
 #class_name: "User"を定義することでUserテーブルのレコードを参照する
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/tweet.rb
class Tweet < ApplicationRecord

  validates :title, presence: true
  validates :description, presence: true

  acts_as_taggable

  belongs_to :user
  attachment :image

  has_many :tweet_comments, dependent: :destroy

  has_many :favorites, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end


end

app/models/tweet_comment.rb
class TweetComment < ApplicationRecord
  # 指定したカラムに何も値が入っていなかったときには保存されない
  validates :rate, presence: true

  belongs_to :user
  belongs_to :tweet

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  validates :last_name, presence: true
  validates :first_name, presence: true

  has_many :tweet_comments, dependent: :destroy

  has_many :tweets, dependent: :destroy
  attachment :profile_image

  has_many :favorites, dependent: :destroy
  has_many :favorite_tweets, through: :favorites, source: :tweet

  has_many :reverth_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverth_of_relationships, source: :follower
  #フォローされた時の関係を通じて参照→followed_idをフォローしている人

  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  #フォローした際の関係を通じて参照→follower_idをフォローしている人

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end

  def rank
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
 #TMDBを使用するために下記を記載
 #rails cを使用しコンソール上でTmdb::Api.key("6202f5cb38f1e6aafa8bd900346a9106")
 # Tmdb::Api.language("ja")を打ち込んで一度読み込ませる必要がある
  require 'themoviedb-api'

  Tmdb::Api.key(ENV["TMDB_API_KEY"])
  Tmdb::Api.language("ja")

  def search
  end

  def show
  end
end

app/controllers/rater_controller.rb
class RaterController < ApplicationController

  def create
    if user_signed_in?
      obj = params[:klass].classify.constantize.find(params[:id])
      obj.rate params[:score].to_f, current_user, params[:dimension]

      render :json => true
    else
      render :json => false
    end
  end
end

app/controllers/tweet_comments_controller.rb
class TweetCommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @tweet = Tweet.find(params[:tweet_id])
    @tweet_comment = TweetComment.new(tweet_comment_params)
    @tweet_comment.tweet_id = @tweet.id
    @tweet_comment.user_id = current_user.id
    if @tweet_comment.save
     redirect_to request.referer, notice: "コメントしました"
    else
     redirect_to request.referer, notice: "コメントできませんでした"
    end
  end

  def destroy
    @tweet = Tweet.find(params[:tweet_id])
    @tweet_comment = @tweet.tweet_comments.find(params[:id])
    @tweet_comment.destroy
  end


  private

  def tweet_comment_params
    params.require(:tweet_comment).permit(:comment, :rate)
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new

  end

  def index
  end

  def show
    @user = User.find(params[:id])
    @tweet = @user.tweets
    @favorite_tweets = @user.favorite_tweets
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render :edit
    else
      redirect_to user_path(current_user)
    end
  end

  def create
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(current_user), notice: "You have update user succssfully."
    else
      render :edit
    end
  end

  def destroy
  end


  private
  def user_params
    params.require(:user).permit(:last_name, :first_name, :profile_image, :introduction)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/tweet_comments_helper.rb
module TweetCommentsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/tweet_comments/_index.html.erb
<h1 class="mt-3">コメント一覧</h1>
<table class="table">
  <thead class="thead-dark">
    <tr>
      <th>名前</th>
      <th>評価</th>
      <th>コメント</th>
      <th>投稿日</th>
      <th> </th>
    </tr>
  </thead>
  <tbody class="border border-dark">
    <% tweet_comments.each do |tweet_comment| %>
      <tr>
        <td class="border border-dark border-right-0"><%= tweet_comment.user.last_name + tweet_comment.user.first_name %></td>
        <td class="movie-rate border border-dark border-left-0 border-right-0" data-score="<%= tweet_comment.rate %>"></td>
        <td class="border border-dark border-right-0 border-dark border-left-0"><%= tweet_comment.comment %></td>
        <td class="border border-dark border-right-0 border-dark border-left-0"><%= tweet_comment.created_at %></td>
        <td class="border border-dark border-left-0">
          <% if tweet_comment.user == current_user %>
            <%= link_to "削除", tweet_tweet_comment_path(tweet_comment.tweet.id, tweet_comment.id), method: :delete, remote: true %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<script>
  $('.movie-rate').raty({
    readOnly: true,
    score: function() {
      return $(this).attr('data-score');
    },
    starOn: "<%= asset_path('star-on.png') %>",
    starOff: "<%= asset_path('star-off.png') %>",
    starHalf: "<%= asset_path('star-half.png') %>",
  });
</script>

app/views/tweet_comments/create.js.erb
$("#comment-<%= @tweet.id %>").html("コメント数: <%= @tweet.tweet_comments.count %>");
$("#tweet-comment-<%= @tweet.id %>").html("<%= j(render 'tweet_comments/index', tweet_comments: @tweet.tweet_comments) %>");
$("textarea").val('');

app/views/tweet_comments/destroy.js.erb
$("#comment-<%= @tweet.id %>").html("コメント数: <%= @tweet.tweet_comments.count %>");
$("#tweet-comment-<%= @tweet.id %>").html("<%= j(render 'tweet_comments/index', tweet_comments: @tweet.tweet_comments) %>");