config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"
  get 'home/about' => 'homes#about'
  get 'home/rank' => 'homes#rank'

  resources :tweets do
   resource :favorites, only: [:create, :destroy]
   resources :tweet_comments, only: [:create, :destroy]
 end

  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
 end

  get 'movies/search'
  get 'movies/show'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :tweet

end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
 #フォロー機能のための記載
 #class_name: "User"を定義することでUserテーブルのレコードを参照する
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/tweet.rb
class Tweet < ApplicationRecord

  validates :title, presence: true
  validates :description, presence: true

  acts_as_taggable

  belongs_to :user
  attachment :image

  has_many :tweet_comments, dependent: :destroy

  has_many :favorites, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end


end

app/models/tweet_comment.rb
class TweetComment < ApplicationRecord
  # 指定したカラムに何も値が入っていなかったときには保存されない
  validates :rate, presence: true

  belongs_to :user
  belongs_to :tweet

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  validates :last_name, presence: true
  validates :first_name, presence: true

  has_many :tweet_comments, dependent: :destroy

  has_many :tweets, dependent: :destroy
  attachment :profile_image

  has_many :favorites, dependent: :destroy
  has_many :favorite_tweets, through: :favorites, source: :tweet

  has_many :reverth_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverth_of_relationships, source: :follower
  #フォローされた時の関係を通じて参照→followed_idをフォローしている人

  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  #フォローした際の関係を通じて参照→follower_idをフォローしている人

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end

  def rank
  end
end

app/controllers/rater_controller.rb
class RaterController < ApplicationController

  def create
    if user_signed_in?
      obj = params[:klass].classify.constantize.find(params[:id])
      obj.rate params[:score].to_f, current_user, params[:dimension]

      render :json => true
    else
      render :json => false
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new

  end

  def index
  end

  def show
    @user = User.find(params[:id])
    @tweet = @user.tweets
    @favorite_tweets = @user.favorite_tweets
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render :edit
    else
      redirect_to user_path(current_user)
    end
  end

  def create
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(current_user), notice: "You have update user succssfully."
    else
      render :edit
    end
  end

  def destroy
  end


  private
  def user_params
    params.require(:user).permit(:last_name, :first_name, :profile_image, :introduction)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-light bg-dark">
    <div class="container">
      <a href="/" class="navbar-brand text-light">Share Theater</a>
      <button class="navbar-toggler text-light bg-light" type="button" data-toggle="collapse" data-target="#navbar9">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="navbar-collapse collapse " id="navbar9">
        <ul class="navbar-nav box d-flex justify-content-end">
        　<% if user_signed_in? %>
        　<li><%= link_to " 新規投稿", new_tweet_path, class:"fas fa-file-upload nav-link text-light"%></li>
        　<li><%= link_to " 投稿一覧", tweets_path, class:"fas fa-clipboard-list nav-link text-light"%></li>
        　<li><%= link_to " マイページ", user_path(current_user.id), class:"fas fa-user nav-link text-light"%></li>
        　<li><%= link_to " 映画検索",  movies_search_path, class:"fas fa-film nav-link text-light"%></li>
        　<li><%= link_to " ログアウト", destroy_user_session_path, method: :delete, class:"fas fa-sign-out-alt nav-link text-light" %></li>
        　<% else %>
        　<li><%= link_to " 投稿一覧", tweets_path, class:"fas fa-clipboard-list nav-link text-light"%></li>
        　<li><%= link_to " About", home_about_path, class:"fas fa-link nav-link text-light"%></li>
        　<li><%= link_to " 会員登録", new_user_registration_path, class:"fas fa-user-plus nav-link text-light"%></li>
        　<li><%= link_to " ログイン", new_user_session_path, class:"fas fa-sign-in-alt nav-link text-light"%></li>
        　<% end %>
        </ul>
      </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Share Theater</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.9.0/css/all.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="bg-secondary">
    <%=render 'layouts/header'%>
    <p id="notice" class="bg-success"><%= notice %></p>
    <%= yield %>
  </body>

</html>